# Generated by Django 4.2.22 on 2025-06-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
    ]
