# Generated by Django 4.2.22 on 2025-06-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderdetail_price_alter_orderdetail_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('accept', 'принят'), ('work', 'в работе'), ('delivery', 'доставка'), ('completed', 'завершён')], db_index=True, default='new', max_length=10),
        ),
    ]
