# Generated by Django 4.2.22 on 2025-06-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('delivery', 'доставка'), ('accept', 'принят'), ('work', 'в работе'), ('completed', 'завершён')], db_index=True, default='new', max_length=10, verbose_name='Статус'),
        ),
    ]
