# Generated by Django 4.2.22 on 2025-06-14 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_comment_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivery', 'доставка'), ('accept', 'принят'), ('completed', 'завершён'), ('work', 'в работе'), ('new', 'новый')], db_index=True, default='new', max_length=10, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='OrderTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='Создание заказа')),
                ('accept', models.DateTimeField(verbose_name='Заказ принят')),
                ('work', models.DateTimeField(verbose_name='Готовка заказа')),
                ('delivery', models.DateTimeField(verbose_name='Доставка заказа')),
                ('completed', models.DateTimeField(verbose_name='Заказ выполнен')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='foodcartapp.order')),
            ],
        ),
    ]
