# Generated by Django 4.2.22 on 2025-06-14 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_order_comment_alter_order_status_ordertime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertime',
            options={'verbose_name': 'Время заказа', 'verbose_name_plural': 'Время заказов'},
        ),
        migrations.RemoveField(
            model_name='ordertime',
            name='creation',
        ),
        migrations.AddField(
            model_name='order',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Создание заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('delivery', 'доставка'), ('work', 'в работе'), ('completed', 'завершён'), ('accept', 'принят')], db_index=True, default='new', max_length=10, verbose_name='Статус'),
        ),
    ]
