# Generated by Django 4.2.22 on 2025-06-15 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_ordertime_options_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='foodcartapp.restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'завершён'), ('work', 'в работе'), ('accept', 'принят'), ('delivery', 'доставка'), ('new', 'новый')], db_index=True, default='new', max_length=10, verbose_name='Статус'),
        ),
    ]
