# Generated by Django 4.2.22 on 2025-06-20 15:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_restaurant_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_accept',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заказ принят'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заказ выполнен'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доставка заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_work',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Готовка заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='foodcartapp.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('accept', 'принят'), ('completed', 'завершён'), ('delivery', 'доставка'), ('work', 'готовят')], db_index=True, default='new', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.DeleteModel(
            name='OrderTime',
        ),
    ]
