# Generated by Django 4.2.22 on 2025-08-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_time_accept_order_time_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'завершён'), ('new', 'новый'), ('accept', 'принят'), ('delivery', 'доставка'), ('work', 'готовят')], db_index=True, default='new', max_length=10, verbose_name='Статус'),
        ),
    ]
